# Generated by Django 5.1.3 on 2025-01-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_toyzum_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
